"use client";

import { useState } from "react";
import { Calendar, Scissors, Search } from "lucide-react";

export type Lang = "fr" | "tn";

export function useLang(initial: Lang = "tn") {
  const [lang, setLang] = useState<Lang>(initial);
  const toggleLang = () => setLang((l) => (l === "fr" ? "tn" : "fr"));
  return { lang, toggleLang };
}

export const home = {
  fr: {
    switchTo: "TN",
    connexion: "Connexion",
    badge: "Réservation instantanée",
    headlineMobile: "L'Élite du Grooming.",
    headlineDesktop1: "L'Élite du ",
    headlineDesktop2: "Grooming.",
    subtitle:
      "Réservez votre coupe en un clic. Précision, style et excellence à portée de main.",
    subtitleAccent: "احجز موعدك الآن",
    ctaClientTitle: "Trouver un coiffeur",
    ctaClientSub: "Pour les clients",
    ctaProTitle: "Espace Barber",
    ctaProSub: "Pour les professionnels",
    trustCount: "+2000 clients",
    trustSub: "réservent déjà via Hajjem",
    guest: "Explorer en invité",
    ratingSub: "+2000 avis clients",
    howTitle: "Réserver n'a jamais été aussi simple",
    howSub:
      "Trois étapes pour votre prochaine coupe, où que vous soyez en Tunisie.",
    steps: [
      {
        icon: Search,
        title: "Trouvez",
        text: "Explorez les meilleurs barbiers près de chez vous, filtrés par ville et service.",
      },
      {
        icon: Calendar,
        title: "Réservez",
        text: "Choisissez un créneau disponible et confirmez votre rendez-vous en un clic.",
      },
      {
        icon: Scissors,
        title: "Profitez",
        text: "Présentez-vous à l'heure et profitez d'un service haut de gamme, sans attente.",
      },
    ],
    copyright: "© 2026 Hajjem. L'élite du grooming en Tunisie.",
  },
  tn: {
    switchTo: "FR",
    connexion: "Dkhol",
    badge: "Rzervation",
    headlineMobile: "L'Elite mta3 Grooming.",
    headlineDesktop1: "L'Elite mta3 ",
    headlineDesktop2: "Grooming.",
    subtitle:
      "Rzervi hjemtek b click wa7ed. Thi9a, style w excellence been yeddek.",
    subtitleAccent: "A7jez maw3dek tawa",
    ctaClientTitle: "Lawaj coiffeur",
    ctaClientSub: "Lel clients",
    ctaProTitle: "Espace Barber",
    ctaProSub: "Lel professionnels",
    trustCount: "+2000 client",
    trustSub: "rzerviw  Hajjem",
    guest: "Chouf men 8ir ma tsajjel",
    ratingSub: "+2000 avis mta3 clients",
    howTitle: "Rzervi hjjemtek 3ad sahla",
    howSub: "Thlatha khatawet lel hjjama lijeya mte3ek, win ma tkoun fi Tounes.",
    steps: [
      {
        icon: Search,
        title: "Lawej",
        text: "Chouf ahsen hajjem 9rib menek, filtration b belled w service.",
      },
      {
        icon: Calendar,
        title: "Rzervi",
        text: "Ekhtar wa9t disponible w confirmi maw3dek b click wa7ed.",
      },
      {
        icon: Scissors,
        title: "Tmatta3",
        text: "Ejri fel wa9t w tmatta3 b service top, bla ma testenna.",
      },
    ],
    copyright: "© 2026 Hajjemi. L'elite mta3 grooming fi Tounes.",
  },
} as const satisfies Record<Lang, unknown>;

export const dashboard = {
  fr: {
    switchTo: "TN",
    nav: {
      dashboard: "Dashboard",
      bookings: "RDV",
      services: "Services",
      profile: "Profil",
    },
    greetingPrefix: "Bonjour",
    todayCount: "RDV Aujourd'hui",
    upcomingTitle: "Prochains Rendez-vous",
    seeAll: "Voir tout",
    confirmed: "Confirmé",
    bookingsTitle: "Rendez-vous",
    pending: "En attente",
    accept: "Accepter",
    decline: "Décliner",
    done: "Terminé",
    myServices: "Mes Services",
    myProfile: "Mon Profil",
    masterBarber: "Maître Barbier",
    bio: "Spécialiste en coupes classiques et entretien de barbe premium. Plus de 10 ans d'expérience au service de l'élégance masculine à Tunis.",
    callAria: "Appeler",
    shareAria: "Partager",
    editProfileAria: "Modifier le profil",
    editServiceAria: "Modifier",
    deleteAria: "Supprimer",
    hours: "Horaires d'ouverture",
    weekdays: "Lundi - Samedi",
    sunday: "Dimanche",
    closed: "Fermé",
    logout: "Déconnexion",
  },
  tn: {
    switchTo: "FR",
    nav: {
      dashboard: "Dashboard",
      bookings: "RDV",
      services: "Services",
      profile: "Profil",
    },
    greetingPrefix: "Ahla",
    todayCount: "RDV Lyoum",
    upcomingTitle: "Rendez-vous Jeyin",
    seeAll: "Chouf kol",
    confirmed: "Mou2akad",
    bookingsTitle: "Rendez-vous",
    pending: "Fil intidhar",
    accept: "E9bel",
    decline: "Orfodh",
    done: "Kamel",
    myServices: "Les Services mte3i",
    myProfile: "Profil mte3i",
    masterBarber: "El M3alem ",
    bio: "Mokhtass fi 9assat classique w e3tina bel le7ya. Aktar men 10 snin khebra fi khedmet l2anaka rjeli fi Tounes.",
    callAria: "3ayet",
    shareAria: "9assem",
    editProfileAria: "Badel Profil",
    editServiceAria: "Badel",
    deleteAria: "Na7i",
    hours: "Wa9t El Khedma",
    weekdays: "Ethnin - Sebt",
    sunday: "El Ahad",
    closed: "Ma8lou9",
    logout: "Khrouj",
  },
} as const satisfies Record<Lang, unknown>;

export const addServiceDialog = {
  fr: {
    add: "Ajouter",
    title: "Nouveau service",
    name: "Nom",
    duration: "Durée",
    price: "Prix",
    cancel: "Annuler",
  },
  tn: {
    add: "Zid",
    title: "Service jdid",
    name: "Esm",
    duration: "Mouda",
    price: "Se3r",
    cancel: "Batel",
  },
} as const satisfies Record<Lang, unknown>;

export const editProfileDialog = {
  fr: {
    editAria: "Modifier le profil",
    title: "Modifier le profil",
    changePhotoAria: "Changer la photo de profil",
    name: "Nom",
    bio: "Description",
    weekdays: "Lundi - Samedi",
    sunday: "Dimanche",
    cancel: "Annuler",
    save: "Enregistrer",
  },
  tn: {
    editAria: "Badel Profil",
    title: "Badel Profil",
    changePhotoAria: "Badel soura mte3 profil",
    name: "Esm",
    bio: "Description",
    weekdays: "Ethnin - Sebt",
    sunday: "El Ahad",
    cancel: "Batel",
    save: "7afedh",
  },
} as const satisfies Record<Lang, unknown>;

export const search = {
  fr: {
    switchTo: "TN",
    navAccueil: "Accueil",
    navSearch: "Trouver un coiffeur",
    navPlans: "Espace Barber",
    avatarAlt: "Portrait de profil de l'utilisateur",
    searchPlaceholder: "Rechercher par ville ou nom...",
    resultsTitleNear: "Coiffeurs à proximité",
    resultsTitleIn: (gov: string) => `Coiffeurs à ${gov}`,
    resultsCount: (n: number) => `${n} résultat${n > 1 ? "s" : ""}`,
    viewProfile: "Voir profil",
    noResults: "Aucun coiffeur trouvé.",
    comingSoon: "Bientôt disponible",
    navHome: "Accueil",
    navExplore: "Explorer",
    navBookings: "RDV",
    navAccount: "Compte",
  },
  tn: {
    switchTo: "FR",
    navAccueil: "Accueil",
    navSearch: "Lawaj coiffeur",
    navPlans: "Espace Barber",
    avatarAlt: "Sourat profil mte3 user",
    searchPlaceholder: "Lawej b belled walla esm...",
    resultsTitleNear: "Hjjama 9rib menek",
    resultsTitleIn: (gov: string) => `Hjjama fi ${gov}`,
    resultsCount: (n: number) => `${n} natija${n > 1 ? "t" : ""}`,
    viewProfile: "Chouf profil",
    noResults: "Ma la9ineh 7ata hajjem.",
    comingSoon: "Jeya 9rib",
    navHome: "Accueil",
    navExplore: "Lawej",
    navBookings: "RDV",
    navAccount: "Compte",
  },
} as const satisfies Record<Lang, unknown>;

export const barberProfile = {
  fr: {
    switchTo: "TN",
    navAccueil: "Accueil",
    navSearch: "Trouver un coiffeur",
    navPlans: "Espace Barber",
    backAria: "Retour",
    open: "Ouvert",
    openShort: "Ouv.",
    closedStatus: "Fermé",
    dateTimeLabel: "Date et heure du rendez-vous",
    dayOffWarning: "Le barbier est fermé ce jour-là. Choisissez un autre jour.",
    noSlots: "Aucun créneau disponible ce jour-là.",
    pickDate: "Choisir une date",
    prevMonthAria: "Mois précédent",
    nextMonthAria: "Mois suivant",
    timeLabel: "Heure",
    confirmPick: "Valider",
    bookingError: "Échec de la réservation. Réessayez.",
    bookingInProgress: "Réservation...",
    bookNow: "Réserver maintenant",
    confirmTitle: "Confirmer la réservation",
    confirmDescription:
      "Vérifiez les détails avant d'envoyer la demande au barbier.",
    confirmDateTime: "Date et heure",
    cancel: "Annuler",
    confirm: "Confirmer",
    sentTitle: "Demande envoyée au barbier",
    sentDescription: (when: string) =>
      `Rendez-vous demandé pour le ${when}. En attente de confirmation du barbier.`,
    ok: "OK",
  },
  tn: {
    switchTo: "FR",
    navAccueil: "Accueil",
    navSearch: "Lawaj coiffeur",
    navPlans: "Espace Barber",
    backAria: "Erj3a",
    open: "Ma7loul",
    openShort: "Ma7.",
    closedStatus: "Ma8lou9",
    dateTimeLabel: "Wa9t maw3dek",
    dayOffWarning: "El barbier maye5damch fel nhar hedha. Ekhtar nhar ekher.",
    noSlots: "Ma fama 7ata créneau disponible fel nhar hedha.",
    pickDate: "Ekhtar date",
    prevMonthAria: "Chahar elli 9bel",
    nextMonthAria: "Chahar elli jey",
    timeLabel: "Wa9t",
    confirmPick: "Valider",
    bookingError: "Rzervation ma najja7tech. 3awed.",
    bookingInProgress: "Rzervation...",
    bookNow: "Rzervi tawa",
    confirmTitle: "Confirmi rzervation",
    confirmDescription: "Chouf details 9bal ma tabaath talab lel hajjem.",
    confirmDateTime: "Date w wa9t",
    cancel: "Batel",
    confirm: "Confirmi",
    sentTitle: "Talab tba3eth lel hajjem",
    sentDescription: (when: string) =>
      `Taleb maw3dek fi ${when}. Fil intidhar el confirmation mta3 el hajjem.`,
    ok: "OK",
  },
} as const satisfies Record<Lang, unknown>;

export const clientAppointments = {
  fr: {
    switchTo: "TN",
    title: "Mes Rendez-vous",
    subtitle: "Suivez l'état de vos réservations.",
    backAria: "Retour",
    pending: "En attente",
    confirmed: "Confirmés",
    cancelled: "Annulés",
    completed: "Terminés",
    statusPending: "En attente",
    statusConfirmed: "Confirmé",
    statusCancelled: "Annulé",
    statusCompleted: "Terminé",
    statusNoShow: "Absence",
    noAppointments: "Aucun rendez-vous pour le moment.",
    navHome: "Accueil",
    navExplore: "Explorer",
    navBookings: "RDV",
    navAccount: "Compte",
    bellAria: "Notifications",
    notifTitle: "Notifications",
    notifEmpty: "Aucune nouvelle notification.",
    notifConfirmed: (name: string, when: string) =>
      `${name} a confirmé votre rendez-vous du ${when}.`,
    notifCancelled: (name: string, when: string) =>
      `${name} a annulé votre rendez-vous du ${when}.`,
    notifClose: "Fermer",
  },
  tn: {
    switchTo: "FR",
    title: "Rendez-vous mte3i",
    subtitle: "Chouf l'état mta3 el rzervations mte3ek.",
    backAria: "Erj3a",
    pending: "Fil intidhar",
    confirmed: "Mou2akdin",
    cancelled: "Mba5lin",
    completed: "Kamlin",
    statusPending: "Fil intidhar",
    statusConfirmed: "Mou2akad",
    statusCancelled: "Mba5el",
    statusCompleted: "Kamel",
    statusNoShow: "Ma jesh",
    noAppointments: "Ma3andekech rendez-vous tawa.",
    navHome: "Accueil",
    navExplore: "Lawej",
    navBookings: "RDV",
    navAccount: "Compte",
    bellAria: "Notifications",
    notifTitle: "Notifications",
    notifEmpty: "Ma3andekech notification jdida.",
    notifConfirmed: (name: string, when: string) =>
      `${name} 9abel maw3dek mta3 ${when}.`,
    notifCancelled: (name: string, when: string) =>
      `${name} refodh maw3dek mta3 ${when}.`,
    notifClose: "Balek",
  },
} as const satisfies Record<Lang, unknown>;

export const clientAccount = {
  fr: {
    switchTo: "TN",
    title: "Mon Compte",
    backAria: "Retour",
    phoneLabel: "Téléphone",
    noPhone: "Aucun numéro renseigné",
    memberSince: (date: string) => `Membre depuis ${date}`,
    logout: "Déconnexion",
    navHome: "Accueil",
    navExplore: "Explorer",
    navBookings: "RDV",
    navAccount: "Compte",
  },
  tn: {
    switchTo: "FR",
    title: "Compte mte3i",
    backAria: "Erj3a",
    phoneLabel: "Telefon",
    noPhone: "Ma fama chi numéro",
    memberSince: (date: string) => `Membre mel ${date}`,
    logout: "Khrouj",
    navHome: "Accueil",
    navExplore: "Lawej",
    navBookings: "RDV",
    navAccount: "Compte",
  },
} as const satisfies Record<Lang, unknown>;

export const editServiceDialog = {
  fr: {
    editAria: "Modifier",
    title: "Modifier le service",
    name: "Nom",
    duration: "Durée",
    price: "Prix",
    cancel: "Annuler",
    save: "Enregistrer",
  },
  tn: {
    editAria: "Badel",
    title: "Badel Service",
    name: "Esm",
    duration: "Mouda",
    price: "Se3r",
    cancel: "Batel",
    save: "7afedh",
  },
} as const satisfies Record<Lang, unknown>;
